### ISSUE TITLE
Callback Not Firing with RunText

### ISSUE THREAD

**Issue by gregoryz7** [meg768/hzeller-matrix#2]
I have incorporated some of your code into mine and after firing the runText 1 time i cant get it to run again without restarting node. I dug into it some and it appears the callback never fires:

```
matrix.runText('incoming',{textColor: 'blue', delay:10}, function(){
        console.log('Scroll Text Complete'); // callback should happen when animation completes
    });
```

The animation completes but the callback never happens. Could you just let me know if you have tested the cb?

Thanks,

**Comment by meg768** [comment]
You are right, the callbacks didn't work properly. I published a new version on npm. It should work now.

**Comment by gregoryz7** [comment]
Thanks! c++ is not my strong point, I went through your addon code for a couple days and couldnt fix it. So i appreciate that!
This is closed, I was hoping that fixing the callback would fix another issue that I have been having with your code but it didn't. I will post more details shortly.
