### ISSUE TITLE
Failed repeated use of runText function

### ISSUE THREAD

**Issue by gregoryz7** [meg768/hzeller-matrix#3]
I wrote this quick example to illustrate the issue i was mentioning in my last post

>  /*
>  Failed Repeated use of runtext function, other functions may have a similar issue
>  */
> var Matrix = require('hzeller-matrix');
> var matrix = new Matrix({width:64, height:32});
> 
> function callback1(){
>       setTimeout(callback2, 6000);
>       matrix.runText('callback1',{textColor: 'blue', delay:10}, function(){
>         console.log('Scroll Text Complete'); // This works fine too, image does scroll
>     });
> }
> function callback2(){
>       console.log('pixel update Complete'); //callback does fire, but image does not work
>       matrix.runText('callback2',{textColor: 'green', delay:10}, function(){  //Does not fire/display anything
>         console.log('Scroll Text Complete');  //does fire
>     });
> }
> matrix.runText('main',{},callback1); //This works fine 

So if I keep sending scrolling messages they will work all day, but if the message ever finishes and i try to send a new message, it no longer will display anything. Some variable might be getting cleared upon animation completion that shouldn't be. I will start to investigate tonight. Interestingly, if you keep sending messages in callbacks they will work fine, so if something is getting cleared it is probably happening after the callback officially ends.

Thanks,
Z

**Comment by meg768** [comment]
Yes, I get the same result as you do. I don't know why the **callback2** doesn't display the text. However, if you don't call **callback2** by using **setTimeout** and instead call it when **callback1** completes, it works.

```
function callback1() {
    // setTimeout(callback2, 6000);
    matrix.runText('callback1',{textColor: 'blue', delay:10}, function(){
        console.log('Scroll Text Complete');
        callback2();
    });
}

function callback2(){
    console.log('pixel update Complete');
    matrix.runText('callback2',{textColor: 'green', delay:10}, function(){
        console.log('Scroll Text Complete');
    });
}

matrix.runText('main',{},callback1);
```

It seems like you may display text once in a **setTimeout** callback but after that, nothing happens. The following code does **not** work as expected.

```
function callback1() {
    matrix.runText('callback1');
}

function callback2() {
    matrix.runText('callback2');
}

setTimeout(callback1, 1000); // Displays fine
setTimeout(callback2, 6000); // Does not display!
```

I will see what I can find out...

**Comment by gregoryz7** [comment]
Also I just used setTimeout as an example. If you have events setup and scrolling is supposed to happen for different events throughout your program. Only the first call will work, unless you keep calling runText before it has a chance to finish displaying.

```
setTimeout(callback1, 1000); // Displays fine
setTimeout(callback1, 1500); // Displays fine interrupts previous message
setTimeout(callback1, 2500); // Displays fine interrupts previous message
setTimeout(callback1, 8000); // Does not display! previous message had already completed before call was made
```

Thanks!
Z

**Comment by meg768** [comment]
Fixed it. You were right. There was a variable **NOT** getting cleared after an animation completed. 

Thanks!

Please let me know if this solved your problem...

**Comment by gregoryz7** [comment]
You fixed it! I tried deleting a couple lines of your code and gave up pretty quickly because i thought the exact opposite was happening :/

Thanks for fixing that so quickly! 
Z
